config:
  target: http://localhost:8080
  phases:
    - duration: 60
      arrivalRate: 0
      rampTo: 50
    - duration: 60
      arrivalRate: 50
    - duration: 60
      arrivalRate: 50
      rampTo: 0
  processor: './scripts/processor.js'
  ensure: 
    p95: 2000
    p99: 3000
  plugins:
    expect: {}
